name: chromosort
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9,<3.13
  - pip
  - minimap2
  - mummer4
  - pillow
  - pytest
  - python-build
  - ruff
  - setuptools>=68
  - wheel
  - pip:
      - -e .
